### ISSUE TITLE
Cannot style inline code separately from <pre> blocks

### ISSUE THREAD

**Issue by jgrg** [mvdkwast/obsidian-copy-as-html#77]
**Is your feature request related to a problem? Please describe.**

I'm writing a custom CSS stylesheet for your excellent plugin.

I'd like to style inline code elements between single backticks with `background-color`, `padding` and `border-radius` properties, so that they look similar to how they appear here on GitHub, but they don't have a class, so I can't select them and my style also gets applied to `<code>` within triple-backquoted `<pre>` blocks.

**Describe the solution you'd like**

Either

- add a style name to the `<code>` elements from single backticks in body text so that I can select them.

or:

- remove the `<code>` markup within the `<pre>` blocks.

**Describe alternatives you've considered**

I did discover this CSS selector, which allows me to apply style to `<code>` which is not within `<pre>` blocks:

```css
code:not(pre > code) {
  color: #aa1111;
  background-color: #ffdee0;
  padding: .2em .4em;
  border-radius: 0.4em;
}
```
I'm not sure how many users would find this, or how widely supported it is. Maybe this is better than setting a class?
